<?php
session_start();
$_SESSION['navi'] = "";
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="Pragma" content="no-cache">
    <title>iAudio</title>
    <link rel="stylesheet" type="text/css" href="scripts/main.css">
  </head>

  <body>
    
    <div id="container">
      
      <?php
        if($this->sessionset)
      		include('navi_login.php');
      	else
      		include('navi_default.php');
      ?>
     
      <div id="main" class="normal">
      
          <p class="big"><u>Registrierung</u></p>
          
          <p style="color: red; font-style: italic; font-weight: bold;">
          <?php
          
          if(!empty($_REQUEST["Error"]) && $_REQUEST["Error"] == "true")
              echo 'Bitte Eingaben überprüfen!';
          else if(!empty($_REQUEST["Error"]) && $_REQUEST["Error"] == "pw")
              echo 'Passwörter stimmen nicht überein!';
          else if(!empty($_REQUEST["Error"]) && $_REQUEST["Error"] == "exists")
              echo 'E-Mailadresse bereits registriert!';
          else
              echo '&nbsp;';
          ?>
          </p>
          
          <form action="/Register/save" enctype="multipart/form-data" method="post" name="options" AUTOCOMPLETE = "off">
              		<table columns="3">
                      <tr>
                        <td colspan="2">Name: </td>
                        <td><input type="text" name="name" value="<?php echo urldecode($_REQUEST["name"]); ?>" style="width: 250px;"></td>
                      </tr>
                      <tr>
                        <td colspan="2">E-Mail: </td>
                        <td><input type="text" name="mail" value="<?php echo urldecode($_REQUEST["mail"]); ?>" style="width: 250px;"></td>
                      </tr>
                      <tr>
                        <td colspan="2">Passwort: </td>
                        <td><input type="password" name="pw" style="width: 250px;"></td>
                      </tr>
                      <tr>
                        <td colspan="2">Passwort wiederholen: </td>
                        <td><input type="password" name="pw_check" style="width: 250px;"></td>
                      </tr>
                      <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td><input name="register" type="submit" value="Registrieren"></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
              	</form>
      
      </div>
    
    </div>
    
  </body>
  
</html>
