<?php
$_SESSION['navi'] = "Verwaltung";
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>iAudio</title>
    <link rel="stylesheet" type="text/css" href="scripts/main.css">
  </head>

  <body>
    
    <div id="container">
      
      <?php
        if($this->sessionset)
      		include('navi_login.php');
      	else
      		include('navi_default.php');
      ?>
     
      <div id="main" class="normal">
      
          <p class="big"><u>Playlistenverwaltung</u></p>
          
          <?php
          if(!empty($_REQUEST["savedPlaylist"]) && $_REQUEST["savedPlaylist"] == "true")
          {
          	  echo '<p style="color: green; font-style: italic; font-weight: bold;">
          	  		Playlist erfolgreich angelegt
          	  		</p>';
          }	
          else
          {
          	  echo '<p style="color: red; font-style: italic; font-weight: bold;">';
	          
          	  if(!empty($_REQUEST["savedPlaylist"]) && $_REQUEST["savedPlaylist"] == "empty")
	              echo 'Bitte Namen für die Playliste angeben!';
	          else if(!empty($_REQUEST["savedPlaylist"]) && $_REQUEST["savedPlaylist"] == "exists")
	              echo 'Sie haben bereits eine Playlist mit diesem Namen!';
	          else
	              echo '&nbsp;';
	              
	          echo '</p>';
          }
          ?>
          
         		 <form action="/Playlist/create" enctype="multipart/form-data" method="post" name="options" AUTOCOMPLETE = "off">
              		<table columns="3">
                      <tr>
                        <td colspan="3"><b>Neue Playlist</b></td>
                      </tr>
                      <tr>
                        <td colspan="2">Bezeichnung: </td>
                        <td><input type="text" name="name"></td>
                      </tr>
                      <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td><input name="create" type="submit" value="anlegen"></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
              	</form>
              	
             <br><br>
             
         <?php
          if(!empty($_REQUEST["renamePlaylist"]) && $_REQUEST["renamePlaylist"] == "true")
          {
          	  echo '<p style="color: green; font-style: italic; font-weight: bold;">
          	  		Playlist erfolgreich umbenannt
          	  		</p>';
          }	
          else
          {
          	  echo '<p style="color: red; font-style: italic; font-weight: bold;">';
	          
          	  if(!empty($_REQUEST["renamePlaylist"]) && $_REQUEST["renamePlaylist"] == "empty")
	              echo 'Bitte geänderten Namen für die Playliste angeben!';
	          else if(!empty($_REQUEST["renamePlaylist"]) && $_REQUEST["renamePlaylist"] == "exists")
	              echo 'Bitte umzunennende Liste auswählen!';
	          else if(!empty($_REQUEST["renamePlaylist"]) && $_REQUEST["renamePlaylist"] == "noList")
	              echo 'Bitte umzunennende Liste auswählen!';
	          else
	              echo '&nbsp;';
	              
	          echo '</p>';
          }
          ?>
          
         		 <form action="/Playlist/rename" enctype="multipart/form-data" method="post" name="options" AUTOCOMPLETE = "off">
              		<table columns="3">
                      <tr>
                        <td colspan="3"><b>Playlist umbenennen</b></td>
                      </tr>
                      <tr>
                      	 <td colspan="2">Playlist: </td>
                      	 <td>
                      	 	<select name="id" size="1">
                               <?php 
                                
                                foreach($this->playlists as $playlist) 
                                {
                                  echo '<option value="'.$playlist["ID"].'">'.$playlist["Name"].'</option>';
                                }
                              
                              ?>
                          	</select>
                        </td>
                      <tr>
                        <td colspan="2">Neue Bezeichnung: </td>
                        <td><input type="text" name="newname"></td>
                      </tr>
                      <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td><input name="rename" type="submit" value="umbenennen"></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
              	</form>
              	
             <br><br>
             
             <?php
          if(!empty($_REQUEST["deletePlaylist"]) && $_REQUEST["deletePlaylist"] == "true")
          {
          	  echo '<p style="color: green; font-style: italic; font-weight: bold;">
          	  		Playlist erfolgreich gelöscht
          	  		</p>';
          }	
          else
          {
          	  echo '<p style="color: red; font-style: italic; font-weight: bold;">';
	          
          	  if(!empty($_REQUEST["deletePlaylist"]) && $_REQUEST["deletePlaylist"] == "empty")
	              echo 'Sie haben keine Playlisten!';
          	  else
	              echo '&nbsp;';
	              
	          echo '</p>';
          }
          ?>
          
         		 <form action="/Playlist/delete" enctype="multipart/form-data" method="post" name="options" AUTOCOMPLETE = "off">
              		<table columns="3">
                      <tr>
                        <td colspan="3"><b>Playlist löschen</b></td>
                      </tr>
                      <tr>
                      	 <td colspan="2">Playlist: </td>
                      	 <td>
                      	 	<select name="id" size="1">
                               <?php 
                                
                                foreach($this->playlists as $playlist) 
                                {
                                  echo '<option value="'.$playlist["ID"].'">'.$playlist["Name"].'</option>';
                                }
                              
                              ?>
                          	</select>
                        </td>
                      <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td><input name="delete" type="submit" value="löschen"></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
              	</form>
              	
             <br><br>

      
      </div>
    
    </div>
    
  </body>
  
</html>
