<?php
$_SESSION['navi'] = "Verwaltung";
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>iAudio</title>
    <link rel="stylesheet" type="text/css" href="scripts/main.css">
  </head>

  <body>
    
    <div id="container">
      
      <?php
        if($this->sessionset)
      		include('navi_login.php');
      	else
      		include('navi_default.php');
      ?>
     
      <div id="main" class="normal">
      
          <p class="big"><u>Willkommen</u></p>
      
      </div>
    
    </div>
    
  </body>
  
</html>
