<?php
session_start();
$_SESSION['navi'] = "";
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="Pragma" content="no-cache">
    <title>iAudio</title>
    <link rel="stylesheet" type="text/css" href="scripts/main.css">
  </head>

  <body>
    
    <div id="container">
      
      <?php
        if($this->sessionset)
      		include('navi_login.php');
      	else
      		include('navi_default.php');
      ?>
     
      <div id="main" class="normal">
      
          <p class="big"><u>Settings</u></p>
          
          
          <?php
          if(!empty($_REQUEST["saved"]) && $_REQUEST["saved"] == "true")
          {
          	  echo '<p style="color: green; font-style: italic; font-weight: bold;">
          	  		Passwort erfolgreich geändert
          	  		</p>';
          }	
          else
          {
          	  echo '<p style="color: red; font-style: italic; font-weight: bold;">';
	          
          	  if(!empty($_REQUEST["pwchange"]) && $_REQUEST["pwchange"] == "false")
	              echo 'Die neuen Passwörter stimmen nicht überein!';
	          else if(!empty($_REQUEST["oldpw"]) && $_REQUEST["oldpw"] == "false")
	              echo 'Das alte Passwort ist falsch!';
	          else
	              echo '&nbsp;';
	              
	          echo '</p>';
          }
          ?>
          
          <form action="/Settings/password" enctype="multipart/form-data" method="post" name="options" AUTOCOMPLETE = "off">
              		<table columns="3">
                      <tr>
                        <td colspan="2">Altes Passwort: </td>
                        <td><input type="password" name="pw_old"></td>
                      </tr>
                      <tr>
                        <td colspan="2">Neues Passwort: </td>
                        <td><input type="password" name="pw"></td>
                      </tr>
                      <tr>
                        <td colspan="2">Neues Passwort wiederholen: </td>
                        <td><input type="password" name="pw_check"></td>
                      </tr>
                      <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td><input name="register" type="submit" value="Passwort ändern"></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
              	</form>
      
      </div>
    
    </div>
    
  </body>
  
</html>
