<?php
$_SESSION['navi'] = "";
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>iAudio</title>
    <link rel="stylesheet" type="text/css" href="scripts/main.css">
  </head>

  <body>
    
    <div id="container">
      
      <?php
        if($this->sessionset)
      		include('navi_login.php');
      	else
      		include('navi_default.php');
      ?>
     
      <div id="main" class="normal">
      
          <p class="big"><u>Musikzuordnung</u></p>
          
          <br><br>
          
         		 <form action="/Play" enctype="multipart/form-data" method="post" name="options" AUTOCOMPLETE = "off">
              		<table columns="3">
                      <tr>
                        <td colspan="3"><b>Playlist abspielen</b></td>
                      </tr>
                      <tr>
                      	 <td colspan="2">Playlist: </td>
                      	 <td>
                      	 	<select name="list" size="1" style="width: 205px;">
                               <?php 
                                
                                foreach($this->playlists as $playlist) 
                                {
                                  if(isset($this->listid) AND $this->listid == $playlist["ID"])
                                  {
                                		echo '<option value="'.$playlist["ID"].'" selected>'.$playlist["Name"].'</option>';
                                		$name = $playlist["Name"];
                                  }
                                  else 
                                  		echo '<option value="'.$playlist["ID"].'">'.$playlist["Name"].'</option>';
                                }
                              
                              ?>
                          	</select>
                        </td>
                      <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td><input name="play" type="submit" value="Abspielen"></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
              	</form>
              	
             <br><br>
             
             <?php 
             
             if(isset($this->m3u))
             {
             	echo 
             	'
				<b><i>Es wird gerade die Playliste \''.$name.'\' abgespielt.</i></b>
				
				<!This code for Netscape>
				<OBJECT ID="MediaPlayer"
				classid="CLSID:22d6f312-b0f6-11d0-94ab-0080c74c7e95"
				CODEBASE="http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=6,4,5,715"
				standby="Loading Microsoft Windows Media Player components..."
				TYPE="application/x-oleobject" width="0" height="0">
				
				<PARAM NAME="FileName" VALUE="'.$this->m3u.'">
				<PARAM NAME="AnimationatStart" VALUE="false">
				<PARAM NAME="TransparentatStart" VALUE="true">
				<PARAM NAME="AutoStart" VALUE="true">
				<PARAM NAME="ShowControls" VALUE="0">
				
				<Embed TYPE="application/x-mplayer2"
				pluginspage="http://www.microsoft.com/isapi/redir.dll?prd=windows&sbp=mediaplayer&ar=Media&sba=Plugin&"
				SRC="'.$this->m3u.'"
				Name=MediaPlayer
				ShowControls=0
				Width=0
				Height=0>
				</embed>
				</OBJECT>
             	';
             }
             
             ?>

      
      </div>
    
    </div>
    
  </body>
  
</html>
