<?php
$_SESSION['navi'] = "Verwaltung";
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>iAudio</title>
    <link rel="stylesheet" type="text/css" href="scripts/main.css">
    
    <script type="text/javascript">
		
		Fenster = null;
		
		function preload()
    	{
			Fenster = window.open("/waiting.html","warten","toolbar=no,menubar=no,top=300,left=300,width=200,height=100")
    	    Fenster.close();
    	}

    	function do_submit() 
	    {
			Fenster = window.open("/waiting.html","warten","toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbar=no,top=" + (screen.height/2 - 60) + ",left=" + (screen.width/2 - 125) + ",width=250,height=125")
    	    Fenster.focus();
	  	  	document.getElementById('upload').submit();
	  	}
    </script>
    
    
  </head>

  <body onload="preload()">
    
    <div id="container">
      
      <?php
        if($this->sessionset)
      		include('navi_login.php');
      	else
      		include('navi_default.php');
      ?>
     
      <div id="main" class="normal">
      
          <p class="big"><u>Musikverwaltung</u></p>
          
          <?php
          if(!empty($_REQUEST["upload"]) && $_REQUEST["upload"] == "true")
          {
          	  echo '<p style="color: green; font-style: italic; font-weight: bold;">
          	  		Musik erfolgreich hochgeladen
          	  		</p>';
          }	
          else
          {
          	  echo '<p style="color: red; font-style: italic; font-weight: bold;">';
	          
          	  if(!empty($_REQUEST["upload"]) && $_REQUEST["upload"] == "empty")
	              echo 'Keine Dateien zum Upload angegeben!';
	          else if(!empty($_REQUEST["size"]) && $_REQUEST["size"] == "true")
	              echo 'Keine gültige Datei angegeben (leer oder größer als 25MB)!';
	          else if(!empty($_REQUEST["extension"]) && $_REQUEST["extension"] == "true")
	              echo 'Es sind nur Dateien mit der Endung .mp3 zugelassen!';
	          else
	              echo '&nbsp;';
	              
	          echo '</p>';
          }
          ?>
          
         		 <form action="/Music/upload" enctype="multipart/form-data" method="post" id="upload" name="options" AUTOCOMPLETE = "off">
              		<table columns="3">
                      <tr>
                        <td colspan="3"><b>Musik hochladen</b></td>
                      </tr>
                      <tr>
                        <td colspan="2">Auswahl: </td>
                        <td><input name="files[]" type="file" style="width: 400px;"/></td>
                      </tr>
                      <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td><button type="button" ytype="save" onclick="do_submit();">Hochladen</button></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
              	</form>
              	
              	<div style="position: absolute; margin-left: 200px; margin-top: -25px">
              		<img name="loading" src="img/statisch.gif" width="200px" height="100px" border="0px">
              	</div>
              	
              	
             <br><br>
             
             <?php
          if(!empty($_REQUEST["delete"]) && $_REQUEST["delete"] == "true")
          {
          	  echo '<p style="color: green; font-style: italic; font-weight: bold;">
          	  		Song erfolgreich gelöscht
          	  		</p>';
          }	
          else
          {
          	  echo '<p style="color: red; font-style: italic; font-weight: bold;">';
	          
          	  if(!empty($_REQUEST["delete"]) && $_REQUEST["delete"] == "empty")
	              echo 'Sie haben keine Songs!';
          	  else
	              echo '&nbsp;';
	              
	          echo '</p>';
          }
          ?>
          
         		 <form action="/Music/delete" enctype="multipart/form-data" method="post" name="options" AUTOCOMPLETE = "off">
              		<table columns="3">
                      <tr>
                        <td colspan="3"><b>Musik löschen</b></td>
                      </tr>
                      <tr>
                      	 <td colspan="2">Song: </td>
                      	 <td>
                      	 	<select name="id" size="1" style="width: 415px;">
                               <?php 
                                
                                foreach($this->music as $music) 
                                {
                                  echo '<option value="'.$music["ID"].'">'.$music["Title"].' ('.$music["Artist"].')</option>';
                                }
                              
                              ?>
                          	</select>
                        </td>
                      <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                      <tr>
                        <td><input name="delete" type="submit" value="Löschen"></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                      </tr>
                    </table>
              	</form>
              	
             <br><br>

      
      </div>
    
    </div>
    
  </body>
  
</html>
